{
  "formatVersion": "1.1",
  "component": {
    "group": "devon.boot.management",
    "module": "devon-boot-management-core",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "devon-boot-management-core-1.0-SNAPSHOT.jar",
          "url": "devon-boot-management-core-1.0-SNAPSHOT.jar",
          "size": 166180,
          "sha512": "5a8be37fb3a74e47c615e4675b275ce09cf0e54aa076742eaf2b7dd78e4994cc5f53bd0f4f23b7220708ddba40a5d8c6dbe91378c10a8bb6990f6977388f29e0",
          "sha256": "5f94463808260caef41020b747baebcb7d393f9aff234eef4c2ee39d9cbe9c62",
          "sha1": "31b83fb52e361a477846ce7e53551fb5c4ac08e7",
          "md5": "60ba2d09eed0e19b046adb0e145efb8c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "devon.boot",
          "module": "devon-boot-starter",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "org.springframework.boot",
              "module": "spring-boot-starter-logging"
            }
          ]
        },
        {
          "group": "devon.boot",
          "module": "devon-boot-starter-log4j2",
          "version": {
            "requires": "1.2"
          },
          "excludes": [
            {
              "group": "org.springframework.boot",
              "module": "spring-boot-starter-logging"
            }
          ]
        },
        {
          "group": "lena",
          "module": "spring-boot-starter-lena",
          "version": {
            "requires": "1.3.1.2"
          },
          "excludes": [
            {
              "group": "org.springframework.boot",
              "module": "spring-boot-starter-logging"
            }
          ]
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-config",
          "version": {
            "requires": "2.2.8.RELEASE"
          },
          "excludes": [
            {
              "group": "org.springframework.boot",
              "module": "spring-boot-starter-logging"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache",
          "version": {
            "requires": "2.3.1.RELEASE"
          },
          "excludes": [
            {
              "group": "org.springframework.boot",
              "module": "spring-boot-starter-logging"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-devtools",
          "version": {
            "requires": "2.3.1.RELEASE"
          },
          "excludes": [
            {
              "group": "org.springframework.boot",
              "module": "spring-boot-starter-logging"
            }
          ]
        },
        {
          "group": "org.apache.tiles",
          "module": "tiles-extras",
          "version": {
            "requires": "3.0.8"
          },
          "excludes": [
            {
              "group": "org.springframework.boot",
              "module": "spring-boot-starter-logging"
            }
          ]
        },
        {
          "group": "org.bitbucket.b_c",
          "module": "jose4j",
          "version": {
            "requires": "0.7.6"
          },
          "excludes": [
            {
              "group": "org.springframework.boot",
              "module": "spring-boot-starter-logging"
            }
          ]
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger-ui",
          "version": {
            "requires": "2.9.2"
          },
          "excludes": [
            {
              "group": "org.springframework.boot",
              "module": "spring-boot-starter-logging"
            }
          ]
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger2",
          "version": {
            "requires": "2.9.2"
          },
          "excludes": [
            {
              "group": "org.springframework.boot",
              "module": "spring-boot-starter-logging"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          },
          "excludes": [
            {
              "group": "org.springframework.boot",
              "module": "spring-boot-starter-logging"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "2.3.1.RELEASE"
          },
          "excludes": [
            {
              "group": "org.springframework.boot",
              "module": "spring-boot-starter-logging"
            }
          ]
        },
        {
          "group": "org.mariadb.jdbc",
          "module": "mariadb-java-client",
          "version": {
            "requires": "1.5.7"
          },
          "excludes": [
            {
              "group": "org.springframework.boot",
              "module": "spring-boot-starter-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "devon-boot-management-core-1.0-SNAPSHOT.jar",
          "url": "devon-boot-management-core-1.0-SNAPSHOT.jar",
          "size": 166180,
          "sha512": "5a8be37fb3a74e47c615e4675b275ce09cf0e54aa076742eaf2b7dd78e4994cc5f53bd0f4f23b7220708ddba40a5d8c6dbe91378c10a8bb6990f6977388f29e0",
          "sha256": "5f94463808260caef41020b747baebcb7d393f9aff234eef4c2ee39d9cbe9c62",
          "sha1": "31b83fb52e361a477846ce7e53551fb5c4ac08e7",
          "md5": "60ba2d09eed0e19b046adb0e145efb8c"
        }
      ]
    }
  ]
}
